spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Willie-lin/eureka-cloud-config.git
          search-paths: config-repo

server:
  port: 12000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
